### ISSUE TITLE
Dataset Issue

### ISSUE THREAD

**Issue by axium** [chaiyujin/glow-pytorch#10]
Thanks for providing a well document implementation of Glow. I am not able to figure out how did you prepare training data for CelebA. I am using your module CelebADataset but failed to produce similar images as you have shown. I tried this module on both aligned cropped version of CelebA and in-the-wild version as well. 

Can you please share you exact data preparation methodology?

**Comment by chaiyujin** [comment]
Hi, @axium I never did any pre-processing.

**Comment by axium** [comment]
My bad! What I mean by pre-processing is the alignment of faces, center cropping etc. Could you tell me which version of CelebA dataset did you use? I am interested in those exact images on which you trained your model on. If you help me understand I would grateful.

**Comment by chaiyujin** [comment]
I use image in dir `img_align_celeba`.  CenterCrop(160) and resize(32)

**Comment by axium** [comment]
Thanks. Really appreciate your help in this. I was making a mistake. Thanks.
