### ISSUE TITLE
Sampling Fails when moving to CIFAR10

### ISSUE THREAD

**Issue by XingangPan** [chaiyujin/glow-pytorch#14]
Thanks for your pytorch version of Glow.
When I am running on CIFAR10 with your code, I find that the reconstruction is generally well, but the model fails to produce reasonable sampling results.
Reconstruction:
![Screenshot from 2019-04-20 17:47:05](https://user-images.githubusercontent.com/13579537/56455715-850c5b80-6394-11e9-93a6-15bab83f0e66.png)
Sampling:
![Screenshot from 2019-04-20 17:44:23](https://user-images.githubusercontent.com/13579537/56455716-8b023c80-6394-11e9-92c7-e8b1bdcf6b90.png)
Do you have any idea how to fix this issue? Thanks.

**Comment by chaiyujin** [comment]
@XingangPan  Have you ever tried lower temperature (sigma) for sampling?

**Comment by XingangPan** [comment]
@chaiyujin Thanks for your suggestion, that might be a reason. 
Anyway, I am moving to https://github.com/pclucas14/pytorch-glow, which works for CIFAR10.

**Comment by chaiyujin** [comment]
@XingangPan  That's great. If you dig some reasons deeper, please tell me. Thanks.
