### ISSUE TITLE
Multiscale Architecture

### ISSUE THREAD

**Issue by Schwartz-Zha** [chaiyujin/glow-pytorch#25]
Is there such a multi-scale architecture in this project?

**Comment by Schwartz-Zha** [comment]
Sorry, a more accurate question should be, in the multi-scale structure presented in the code (in class FlowNet), each iteration in L will make (N,C,H,W) turn to (N, C*2, H/2, W/2). The point is just to enlarge the channel number, right? Then where is the operation to get the shape back? And I didn't see any "checkerboard masks" as mentioned in paper "Density Estimation Using Real NVP".

**Comment by chaiyujin** [comment]
With `reverse=True`, it should recover the shape.

**Comment by Schwartz-Zha** [comment]
Okay! Thanks! Got it.
