### ISSUE TITLE
Question about Affine Coupling Parameterisation

### ISSUE THREAD

**Issue by angusturner** [chaiyujin/glow-pytorch#3]
I noticed in your affine coupling you are doing:
```
scale = F.sigmoid(scale + 2)
```

As opposed to the RealNVP parameterisation:
```
scale = scale.exp()
```

Did you find the sigmoid necessary for stability? It seems unusual to me, because it means that the feature-wise transformations can only contract/shrink the input space at every layer.

**Comment by angusturner** [comment]
Edit: never mind, I noticed they have done this in the original code too. Seems to be necessary for stability of deeper models.

**Comment by voletiv** [comment]
Hi, in the RealNVP paper, tanh is used:
"To compute the scaling functions s, we use a hyperbolic tangent function multiplied by a learned
scale, whereas the translation function t has an affine output."

So maybe use tanh instead of sigmoid?
