### ISSUE TITLE
Would you like share us pre-trained model?

### ISSUE THREAD

**Issue by delldu** [chaiyujin/glow-pytorch#4]
Dear Sir,
    We appreciate your projects, thank you in advance.
    It would be better if you can share us your pre-trained model. Would you like  ?

**Comment by chaiyujin** [comment]
Oh, I forgot to upload my pre-trained model. I will upload to DropBox.
BTW, I have a plan to train on HQ dataset, but not recently.

**Comment by chaiyujin** [comment]
I have upload to dropbox. See readme

**Comment by delldu** [comment]
Many thanks.
